# sudo apt install openssh-server openssh-client -y
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# wget https://archive.apache.org/dist/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz && tar -xzvf hadoop-3.3.0.tar.gz
export HADOOP_HOME=/root/infrastructure/spark/hadoop-3.3.0
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME

export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
# export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$JAVA_HOME/bin
export HADOOP_INSTALL=$HADOOP_HOME