version: "3"
x-common:
  &common
  # restart: always
  oom_kill_disable: true
  logging:
    options:
      max-file: "5"
      max-size: "128m"
  shm_size: 3g
  mem_limit: 4g
  cpus: 2
  networks:
    - bridge_default
  volumes:
    - "./spark/logs:/opt/bitnami/spark/logs:rw"
    # - "./spark/conf:/opt/bitnami/spark/conf:rw"
    - "./spark/work:/opt/bitnami/spark/work:rw"
    - "./spark/tmp:/opt/bitnami/spark/tmp:rw"
    - "./tmp:/tmp:rw"

services:
  spark:
    <<: *common
    image: docker.io/bitnami/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    expose:
      - 8080
      - 7077

  spark-worker:
    <<: *common
    image: docker.io/bitnami/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8081:8081'
    expose:
      - 8081

networks:
  bridge_default:
    driver: bridge
