version: "3"
x-common:
  &common
  # restart: always
  oom_kill_disable: true
  logging:
    options:
      max-file: "5"
      max-size: "128m"
  shm_size: 3g
  mem_limit: 4g
  cpus: 2
  networks:
    - bridge_default
  volumes:
    - "./spark/logs:/spark/logs:rw"
    - "./spark/conf:/spark/conf:rw"
    - "./spark/work:/spark/work:rw"
    - "./spark/tmp:/spark/tmp:rw"
    - "./tmp:/tmp:rw"

services:
  spark-master:
    <<: *common
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - '8080:8080'
      - '7077:7077'
    expose:
      - 8080
      - 7077

  spark-worker:
    <<: *common
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    ports:
      - '8081:8081'
    expose:
      - 8081

networks:
  bridge_default:
    driver: bridge
